---
- name: Gather Facts from Server
  hosts: 10.128.18.11
  gather_facts: true
  vars:
    ansible_user: forward
    ansible_ssh_common_args: "-o ProxyJump=forward@deveci-jump"

  tasks:
    - name: Display Gathered Facts
      ansible.builtin.debug:
        var: ansible_facts
