- name: Gather IP Information from Linux Server via Jump Server
  hosts: localhost
  gather_facts: false

  vars:
    jump_server_credential: deveci-jump
    remote_server_hostname: deveci-jump
    command_to_run: "ip a"

  tasks:
    - name: Log into Jump Server
      ansible.builtin.shell: echo "Logging into Jump Server"
      delegate_to: localhost
      run_once: true

    - name: Set Remote Server Login Parameters
      set_fact:
        remote_login_params:
          become: no  # Disable privilege escalation
          ansible_user: "{{ lookup('community.general.credential', jump_server_credential).username }}"
          ansible_ssh_common_args: "-o ProxyJump={{ remote_server_hostname }}"

    - name: Run Command on Remote Server
      ansible.builtin.shell:
        cmd: "{{ command_to_run }}"
      delegate_to: "{{ remote_server_hostname }}"
      environment:
        ANSIBLE_SSH_ARGS: "{{ deveci.credential_password }}"
      with_items: "{{ remote_login_params | default([]) }}"  # Use the login parameters

    - name: Display Command Output
      ansible.builtin.debug:
        var: ansible_stdout_lines
      run_once: true
