---
- name: Ping IP Address
  hosts: 10.128.18.11
  gather_facts: false

  tasks:
    - name: Ping IP Address
      ansible.builtin.ping:
        data: "{{ hostvars['localhost'].ansible_default_ipv4.address }}"
