---
- name: Gather Facts from Remote Device via Jump Server with AWX Credentials
  hosts: localhost
  gather_facts: false
  vars:
    jump_server_awx_credential: deveci-jump
    remote_device_awx_credential: FlexVPN
  tasks:
    - name: Configure Jump Server Connection
      ansible.builtin.ansible_connection: ssh
      ansible.builtin.ansible_user: forward
      ansible.builtin.ansible_host: deveci-jump
      ansible.builtin.ansible_password: '{{ deveci-jump.credential_password }}'

    - name: Gather Facts from Remote Device
      gather_facts: true
      vars:
        ansible_user: forward
        ansible_ssh_pass: '{{ FlexVPN.credential_password }}'
      tasks:
        - name: Display Gathered Facts
          ansible.builtin.debug:
            var: ansible_facts
