---
- name: Log into Linux Server and Run ip a
  hosts: localhost
  gather_facts: false

  vars:
    remote_server_host: "{{ deveci_jump }}"  # Assuming you have the IP defined for the machine
    remote_username: "{{ machine.deveci_jump }}"
    remote_password: "{{ machine.deveci_jump }}"

  tasks:
    - name: Log into remote server and run ip a
      ansible.builtin.expect:
        command: ssh "{{ remote_username }}"@"{{ remote_server_host }}" ip a
        responses:
          (?i)password: "{{ remote_password }}"
      register: ssh_output

    - debug:
        var: ssh_output.stdout_lines


