- name: Connect to Network Device via Jump Server
  hosts: jump_server
  gather_facts: false
  tasks:
    - name: Connect to Jump Server
      ansible.builtin.ping

- name: Run NetCLI Commands on Network Device
  hosts: network_devices
  gather_facts: false
  tasks:
    - name: Issue NetCLI Command
      ansible.builtin.netmiko_send_command:
        command_string: show version