- name: Gather IP Information from Linux Server via Jump Server
  hosts: localhost
  gather_facts: false

  vars:
    jump_server_credential: deveci-jump
    remote_server_hostname: deveci-jump
    command_to_run: "ip a"

  tasks:
    - name: Log into Jump Server
      ansible.builtin.shell: echo "Logging into Jump Server"
      delegate_to: localhost
      run_once: true

    # Comment out the next tasks and gradually reintroduce them to isolate the issue

    - name: Display Debug Message
      ansible.builtin.debug:
        msg: "This is a debug message"
