---
- name: Ping IP Address
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Ping IP Address
      ansible.builtin.ping:
        data: "{{ hostvars['localhost'].ansible_default_ipv4.address }}"
