- name: Gather IP Information from Linux Server via Jump Server
  hosts: localhost
  gather_facts: false

  vars:
    jump_server_credential: deveci-jump
    remote_server_hostname: deveci-jump
    remote_user: forward  # Specify the desired username
    command_to_run: "ip a"

  tasks:
    - name: Log into Jump Server
      ansible.builtin.shell: echo "Logging into Jump Server"
      delegate_to: localhost
      run_once: true

    - name: Run Command on Remote Server
      ansible.builtin.shell: "{{ command_to_run }}"
      delegate_to: "{{ remote_server_hostname }}"
      environment:
        ANSIBLE_SSH_ARGS: "{{ deveci.credential_password }}"
      with_items: []
      become: yes
      become_user: "{{ remote_user }}"  # Specify the desired username for privilege escalation

    - name: Display Command Output
      ansible.builtin.debug:
        var: ansible_stdout_lines
      run_once: true
