---
- name: Log into Linux Server and Prompt for Password
  hosts: localhost
  gather_facts: false

  vars:
    remote_server_ip: deveci-jump  # Replace with your Linux server's IP
    remote_username: forward

  tasks:
    - name: Prompt for Password
      ansible.builtin.expect:
        command: ssh {{ remote_username }}@{{ remote_server_ip }}
        responses:
          "assword.*": "{{ lookup('password', '/dev/null chars=ascii_letters,digits,punctuation length=16') }}"
      delegate_to: localhost
      run_once: true
