---
- name: Ping Jump Server
  hosts: jump_server_hostname
  tasks:
    - name: Ping the server
      ping:
      register: ping_result

    - name: Display ping result
      debug:
        msg: "{{ ping_result }}"
